apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - awsnotetemplate-critical.yaml
  - awsnotetemplate-default.yaml
  - provisioner-critical.yaml
  - provisioner-default.yaml
