apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-1
spec:
  providerRef:
    name: default-1
  labels:
    node.dex4er.github.com/default: "true"
  requirements:
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values:
        - t
        - m
    - key: karpenter.k8s.aws/instance-cpu
      operator: In
      values:
        - "2"
    # - key: karpenter.k8s.aws/instance-memory
    #   operator: In
    #   values:
    #     - "8192"
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values:
        - nano
        - micro
        - 12xlarge
        - 16xlarge
        - 18xlarge
        - 24xlarge
    - key: topology.kubernetes.io/zone
      operator: In
      values:
        - ${azs_name_0}
    - key: ubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - spot
        - on-demand
  kubeletConfiguration:
    clusterDNS:
      - 10.100.0.10
    containerRuntime: containerd
    # maxPods: 29
  limits:
    resources:
      cpu: 10k
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 3600
  weight: 1
