apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: critical-1
spec:
  providerRef:
    name: critical-1
  taints:
    - key: CriticalAddonsOnly
      value: "true"
      effect: NoSchedule
  labels:
    node.dex4er.github.com/critical: "true"
  requirements:
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: [m]
    - key: karpenter.k8s.aws/instance-generation
      operator: In
      values: ["5"]
    - key: karpenter.k8s.aws/instance-cpu
      operator: In
      values: ["2"]
    - key: topology.kubernetes.io/zone
      operator: In
      values: ["${azs_name_0}"]
    - key: ubernetes.io/arch
      operator: In
      values: [amd64]
    - key: karpenter.sh/capacity-type
      operator: In
      values: [spot]
  kubeletConfiguration:
    clusterDNS: [10.100.0.10]
    containerRuntime: containerd
    maxPods: 29
  ttlSecondsAfterEmpty: 30
  weight: 1
