apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-node-role-label
subjects:
  - kind: ServiceAccount
    name: eks-node-role-label
    namespace: eks-node-role-label
roleRef:
  kind: ClusterRole
  name: eks-node-role-label
  apiGroup: rbac.authorization.k8s.io
