apiVersion: batch/v1
kind: CronJob
metadata:
  name: eks-node-role-label
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  concurrencyPolicy: Forbid
  schedule: "* * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  startingDeadlineSeconds: 60
  jobTemplate:
    spec:
      template:
        metadata:
          name: eks-node-role-label
          labels:
            app: eks-node-role-label
        spec:
          serviceAccountName: eks-node-role-label
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl:1.23.13
              command:
                - /bin/bash
              args:
                - -euc
                - |
                  kubectl get node -L eks.amazonaws.com/nodegroup,karpenter.sh/provisioner-name |
                  while read -r name status roles age version nodegroup provisioner; do
                    if [[ ${roles} = "<none>" ]]; then
                      if [[ -n ${nodegroup} ]]; then
                        kubectl label node ${name} node-role.kubernetes.io/${nodegroup}=
                      elif [[ -n ${provisioner} ]]; then
                        kubectl label node ${name} node-role.kubernetes.io/${provisioner}=
                      fi
                    fi
                  done
              resources:
                requests:
                  cpu: 100m
                  memory: 64Mi
                limits:
                  cpu: "666"
                  memory: 64Mi
          tolerations:
            - effect: NoSchedule
              key: CriticalAddonsOnly
              operator: Equal
              value: "true"
