apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eks-node-role-label
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - cronjob.yaml
  - namespace.yaml
  - poddisruptionbudget.yaml
  - serviceaccount.yaml
