apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: karpenter-provisioners
  namespace: flux-system
spec:
  dependsOn:
    - name: karpenter
  interval: 1m
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: ./karpenter-provisioners
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
